proxy_type: auto
sketchbook_path: .\
arduino_data: .\external
board_manager:
  additional_urls:
    - https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
    - http://arduino.esp8266.com/stable/package_esp8266com_index.json
