version: 0.0.{build}
image: Visual Studio 2015
environment:
  PATH: '%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin'
build_script:
- cmd: make.exe
test: off
artifacts:
- path: Nemesis-Mod/Nemesis-Mod.arduino.avr.uno.hex
- path: Nemesis-Mod/Nemesis-Mod.arduino.avr.uno.elf
deploy: off