version: 0.0.{build}
image: Visual Studio 2015

environment:
  PATH: '%PATH%;C:\MinGW\bin;C:\MinGW\msys\1.0\bin'

build_script:
- cmd: make.exe

artifacts:
- path: out/Mainboard.ino.zip
- path: out/Mainboard.ino.hex
- path: out/Mainboard.ino.elf
- path: out/Mainboard.ino.map

deploy: off