name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make
    
    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: build/Nemesis-Mod.ino.*