name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Upload mainboard
      uses: actions/upload-artifact@v2
      with:
        name: sketches
        path: out/Mainboard/Mainboard.ino.bin

    - name: Extract files
      run: 7z e ${env:GITHUB_WORKSPACE}/out/Bluetooth/Bluetooth.ino.zip -o"${env:GITHUB_WORKSPACE}/out/Bluetooth"

    - name: Upload bluetooth
      uses: actions/upload-artifact@v2
      with:
        name: sketches
        path: out/Bluetooth/Bluetooth.ino.bin

  package:
    runs-on: windows-latest
    timeout-minutes: 15
    needs: build

    steps:
    - name: Checkout packager
      uses: actions/checkout@v2
      with:
        repository: microsoft/uf2
        path: uf2
    
    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Download sketches
      uses: actions/download-artifact@v2
      with:
        name: sketches
        path: bin

    # The values passed into the script need to be retrieved from the following page:
    # See: https://learn.adafruit.com/adafruit-feather-m4-express-atsamd51/uf2-bootloader-details
    - name: Package mainboard
      run: python uf2/utils/uf2conv.py -c -b 0x4000 -o ${env:GITHUB_WORKSPACE}/mainboard.uf2 ${env:GITHUB_WORKSPACE}/bin/Mainboard.ino.bin

    # The values passed into the script need to be retrieved from the following page:
    # See: https://github.com/adafruit/Adafruit_nRF52_Bootloader
    - name: Package bluetooth
      run: python uf2/utils/uf2conv.py -c -b 0x26000 -f 0xADA52840 -o ${env:GITHUB_WORKSPACE}/bluetooth.uf2 ${env:GITHUB_WORKSPACE}/bin/Bluetooth.ino.bin

    - name: Upload mainboard
      uses: actions/upload-artifact@v2
      with:
        name: mainboard
        path: mainboard.uf2

    - name: Upload bluetooth
     uses: actions/upload-artifact@v2
     with:
       name: bluetooth
       path: bluetooth.uf2