name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Upload mainboard
      uses: actions/upload-artifact@v2
      with:
        name: mainboard
        path: out/Mainboard/Mainboard.ino.*

    - name: Upload bluetooth
      uses: actions/upload-artifact@v2
      with:
        name: bluetooth
        path: out/Bluetooth/Bluetooth.ino.*

  package:
    runs-on: windows-latest
    timeout-minutes: 15
    needs: build

    steps:
    - name: Checkout packager
      uses: actions/checkout@v2
      with:
        repository: microsoft/uf2
        path: uf2
    
    - name: Download mainboard
      uses: actions/download-artifact@v2
      with:
        name: mainboard
        path: out/mainboard

    - name: Download bluetooth
      uses: actions/download-artifact@v2
      with:
        name: bluetooth
        path: out/bluetooth
    
    - name: Decompress Bluetooth.ino.zip
      run: 7z x out/bluetooth/Bluetooth.ino.zip