name: CI

on: [ push, pull_request ]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make

    - name: Upload mainboard
      uses: actions/upload-artifact@v2
      with:
        name: mainboard
        path: out/Mainboard/Mainboard.ino.*

    - name: Upload bluetooth
      uses: actions/upload-artifact@v2
      with:
        name: bluetooth
        path: out/Bluetooth/Bluetooth.ino.*

  package:
    runs-on: windows-latest
    timeout-minutes: 15
    needs: build

    steps:
    - name: Checkout packager
      uses: actions/checkout@v2
      with:
        repository: microsoft/uf2
        path: uf2
    
    - name: Download mainboard
      uses: actions/download-artifact@v2
      with:
        name: mainboard
        path: out/mainboard

    - name: Package mainboard
      run: uf2/utils/uf2conv.py -c -b 0x4000 -o out/mainboard.uf2 out/mainboard/mainboard.ino.bin

    - name: Download bluetooth
      uses: actions/download-artifact@v2
      with:
        name: bluetooth
        path: out/bluetooth
    
    - name: Decompress bluetooth
      run: 7z x out/bluetooth/Bluetooth.ino.zip

    - name: Package bluetooth
      run: uf2/utils/uf2conv.py -c -b 0x4000 -o out/bluetooth.uf2 out/bluetooth/Bluetooth.ino.bin

    - name: Upload mainboard.uf2
      uses: actions/upload-artifact@v2
      with:
        name: mainboard
        path: out/mainboard.uf2

    - name: Upload bluetooth.uf2
      uses: actions/upload-artifact@v2
      with:
        name: bluetooth
        path: out/bluetooth.uf2