name: Release

on:
 release:
   types: [created]

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 15

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build
      run: make
    
    - name: Upload mainboard
      uses: actions/upload-artifact@v2
      with:
        name: mainboard
        path: out/Mainboard/Mainboard.ino.*

    - name: Upload bluetooth
      uses: actions/upload-artifact@v2
      with:
        name: bluetooth
        path: out/Bluetooth/Bluetooth.ino.*